Repository ShumbaBrown/Project-Sia, pull requests merged in 2020-02, with the labels that each got.

#48 Fleshed out README
  README.md
Labels: documentation

#49 Added event definition and appropriate test suite.
  project_sia/src/event.js
  project_sia/src/test_suite/event.test.js
Labels: backend, high priority

#50 Added Date to events. Created user. Updated tests.
  project_sia/src/event.js
  project_sia/src/test_suite/event.test.js
  project_sia/src/test_suite/user.test.js
  project_sia/src/user.js
Labels: backend

#53 Dev backend
  .DS_Store
  project_sia/src/Backend.js
  sia-react-native/Backend.js
  sia-react-native/classes/event.js
  sia-react-native/classes/user.js
  sia-react-native/screens/Home.js
  sia-react-native/screens/Login.js
Labels: backend
