Repository ShumbaBrown/Project-Sia, pull requests merged in 2020-04, with the labels that each got.

#69 Added support for arr type stats
  project_sia/src/native_test_suite/achievement.test.js
  project_sia/src/native_test_suite/statistic.test.js
  project_sia/src/native_test_suite/statisticList.test.js
  project_sia/src/native_test_suite/user.test.js
  sia-react-native/classes/achievement.js
  sia-react-native/classes/statistic.js
Labels: backend, enhancement

#70 Added default user statistic
  project_sia/src/native_test_suite/user.test.js
  sia-react-native/classes/user.js
Labels: backend

#71 Backend support for statistic
  package-lock.json
  sia-react-native/Backend.js
Labels: backend

#73 Adding front end updates
  sia-react-native/App.js
  sia-react-native/assets/bisonlogo.png
  sia-react-native/assets/link.png
  sia-react-native/assets/microsoft.png
  sia-react-native/assets/protest.png
  sia-react-native/assets/resumebuilding.png
  sia-react-native/assets/sialogo.png
  sia-react-native/assets/tyrone.png
  sia-react-native/assets/zumba.png
  sia-react-native/navigation/SwitchNavigator.js
  sia-react-native/screens/AchievementList.js
  sia-react-native/screens/EventCard.js
  sia-react-native/screens/EventForm.js
  sia-react-native/screens/EventListFront.js
  sia-react-native/screens/Home.js
  sia-react-native/screens/Login.js
  sia-react-native/screens/News.js
  sia-react-native/screens/Notifications.js
  sia-react-native/screens/components/Links.js
  sia-react-native/screens/components/SampEvents.js
  sia-react-native/screens/components/Tag.js
Labels: enhancement, frontend

#74 Updating components relating to events functionality
  sia-react-native/screens/EventCard.js
  sia-react-native/screens/EventForm.js
  sia-react-native/screens/EventListFront.js
Labels: enhancement, frontend
